### ISSUE TITLE
Bot cant jump into that structure for no reason. It stucks in the corner

### ISSUE THREAD

**Issue by Grammf** [PrismarineJS/mineflayer-pathfinder#283] opened 2022-07-30 16:04 UTC
![2022-07-30_19 00 29](https://user-images.githubusercontent.com/89208604/181925231-193b4379-3c5c-478a-aa0f-572dcdf2baa1.png)
![2022-07-30_19 03 11](https://user-images.githubusercontent.com/89208604/181925337-09dc19a6-1655-45cf-87f8-6f42c9d0f35b.png)

**Comment by IceTank** [comment] 2022-08-12 11:18
Will look at this when I have time

**Comment by IceTank** [comment] 2022-08-21 09:03
Cannot reproduce. Did you use GoalNear instead off goal block?

**Comment by IceTank** [comment] 2022-09-08 18:08
Closing this now

**Closed by IceTank** 2022-09-08 18:08 UTC
