### ISSUE TITLE
Digging through blocks in >=1.2.0 is incredibly slow and unresponsive

### ISSUE THREAD

**Issue by SoLegendary** [PrismarineJS/mineflayer-pathfinder#91] opened 2020-12-25 11:35 UTC
When a goal requiring digging through blocks is set (eg. underground, inside stone/dirt) the bot appears incredibly slow to start and continue digging, occasionally freezing entirely without moving. This happens for any kind of material and whether or not it has a tool available. 

The earliest version this happens in is 1.2.0, if I downversion to 1.1.2 the issue disappears and the bot mines at normal speed through blocks towards the goal. It also disappears if movements.digCost is set to 0 even in 1.2.0.

I'm using this with Mineflayer 2.39.2 and NodeJS v15.5.0

**Comment by Karang** [comment] 2021-01-07 23:25
Does this still happen in 1.3.0 ? I'm not able to reproduce the issue, please provide more details.

**Comment by Karang** [comment] 2021-01-10 12:56
Should be fixed in 1.3.5, reopen if you still have the issue.

**Closed by Karang** 2021-01-10 12:56 UTC
