### ISSUE TITLE
Pathfinder cannot handle traveling downwards / Add a Waterbucket Option

### ISSUE THREAD

**Issue by GenerelSchwerz** [PrismarineJS/mineflayer-pathfinder#95] opened 2021-01-07 13:12 UTC
Currently, there's no option to have the pathfinding algorithm ignore fall damage. If the bot could ignore calculating for fall damage, water bucketing could be a far better option then gradually building downwards to get to its goal.

Right now, the bot is incapable of following players if they head downward. Having toggleable options (similar to baritone's options) such as "ignore fall damage, avoid liquid radius, assume Jesus (liquids act like solid blocks), assume no blocks, etc.". would make the plugin in general much more versatile.

**Comment by Karang** [comment] 2021-01-07 23:20
You could already modify the maxDropDown option of the movement generator.
In v1.3.0 the bot can drop in water from high places. Waterbucket still need to be implemented.

**Comment by Karang** [comment] 2021-01-07 23:23
Duplicate of #31

**Closed** 2021-01-07 23:23 UTC
